//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMOA.WorkWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMOA.WorkWeb.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 zh-cn 的本地化字符串。
        /// </summary>
        public static string _culture {
            get {
                return ResourceManager.GetString("_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号 的本地化字符串。
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancellation 的本地化字符串。
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string captcha {
            get {
                return ResourceManager.GetString("captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 换一张 的本地化字符串。
        /// </summary>
        public static string changeone {
            get {
                return ResourceManager.GetString("changeone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2019-2024 某某科技 xx.com All Rights Reserved 的本地化字符串。
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行政 的本地化字符串。
        /// </summary>
        public static string dp_as {
            get {
                return ResourceManager.GetString("dp_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客服 的本地化字符串。
        /// </summary>
        public static string dp_cs {
            get {
                return ResourceManager.GetString("dp_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 研发 的本地化字符串。
        /// </summary>
        public static string dp_rd {
            get {
                return ResourceManager.GetString("dp_rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登入 的本地化字符串。
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆失败,用户名或密码错误 的本地化字符串。
        /// </summary>
        public static string loginfailed {
            get {
                return ResourceManager.GetString("loginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登出 的本地化字符串。
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤 的本地化字符串。
        /// </summary>
        public static string menu_attendance {
            get {
                return ResourceManager.GetString("menu_attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门管理 的本地化字符串。
        /// </summary>
        public static string menu_department {
            get {
                return ResourceManager.GetString("menu_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string menu_group {
            get {
                return ResourceManager.GetString("menu_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工时 的本地化字符串。
        /// </summary>
        public static string menu_hours {
            get {
                return ResourceManager.GetString("menu_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选单管理 的本地化字符串。
        /// </summary>
        public static string menu_memu {
            get {
                return ResourceManager.GetString("menu_memu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目设定 的本地化字符串。
        /// </summary>
        public static string menu_projects {
            get {
                return ResourceManager.GetString("menu_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表管理 的本地化字符串。
        /// </summary>
        public static string menu_report {
            get {
                return ResourceManager.GetString("menu_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目管理 的本地化字符串。
        /// </summary>
        public static string menu_revenue {
            get {
                return ResourceManager.GetString("menu_revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理 的本地化字符串。
        /// </summary>
        public static string menu_system {
            get {
                return ResourceManager.GetString("menu_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string menu_user {
            get {
                return ResourceManager.GetString("menu_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code已存在 的本地化字符串。
        /// </summary>
        public static string ormsg_codeexist {
            get {
                return ResourceManager.GetString("ormsg_codeexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string ormsg_role_1 {
            get {
                return ResourceManager.GetString("ormsg_role_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色被引用 的本地化字符串。
        /// </summary>
        public static string ormsg_role_2 {
            get {
                return ResourceManager.GetString("ormsg_role_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号重复 的本地化字符串。
        /// </summary>
        public static string ormsg_user_1 {
            get {
                return ResourceManager.GetString("ormsg_user_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱重复 的本地化字符串。
        /// </summary>
        public static string ormsg_user_2 {
            get {
                return ResourceManager.GetString("ormsg_user_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string passwrod {
            get {
                return ResourceManager.GetString("passwrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string role_admin {
            get {
                return ResourceManager.GetString("role_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工 的本地化字符串。
        /// </summary>
        public static string role_emp {
            get {
                return ResourceManager.GetString("role_emp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主管 的本地化字符串。
        /// </summary>
        public static string role_manager {
            get {
                return ResourceManager.GetString("role_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        public static string role_test {
            get {
                return ResourceManager.GetString("role_test", resourceCulture);
            }
        }
    }
}
