var PageResx = {
    col_Name: '任务',
    col_project : '项目',
    col_EndTime: '截至时间',
    col_Estimate: '预计工时',
    col_Consume: '消耗工时',
    col_Sort: '优先级',
    col_State: '状态',
    col_CreateTime: '创建时间',
    col_listTeam: '成员',
    col_oper: '操作',
    confirm: "你确定设置该项为:",
    confirm_reset: "重置",
    confirm_start: "启动",
    confirm_accomplish: "完成",
    confirm_cancel: "取消",
    confirm_close: "关闭",
    confirm_subtask: "子任务",

}